# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      GRADLE_OPTS: -Xmx512m -Xms512m -Dorg.gradle.parallel.intra=true -Dorg.gradle.daemon=false

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-gradle-{{ .Branch }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "gradle/dependencies.gradle" }}
            - v1-gradle-{{ .Branch }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - v1-gradle-{{ .Branch }}
            - v1-gradle-master
            - v1-gradle

      - run: ./gradlew downloadDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-gradle-{{ .Branch }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "gradle/dependencies.gradle" }}

      # run sanity check
      - run: ./gradlew sanityCheck --max-workers=4 --parallel
      - run: ./gradlew :ratpack-site:check :ratpack-core:check build jacocoReport --max-workers=4 --parallel --continue

